<?xml version="1.0"?>
<package format="3">
  <name>laser_uav_simulation</name>
  <version>1.0.0</version>
  <description>LaSER UAV Simulation</description>
  <maintainer email="augustoviniciud@gmail.com">Augusto Vinicius F. de Sales</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>laser_gazebo_resources</depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
